	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'MAMMALS');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'BIRDS');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'REPTILES');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'ADMINISTRATION');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'SECURITY');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'CLEANING');

  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Al' , 'Abranow' , 'f', null, 'Mammals', 1);
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Betty', 'Brunowska', 
  'F', null, 'Birds', 2); 
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Cezar', 'Cejrus', 'M', null, 'Reptiles', 3);
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Dominik' , 'De Vitto',  'M', null, null, 4);
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Eve', 'Evans',  'F', null, null, 4);

  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextval, 'Anatol' , 'lion', 'M',
  '2013-01-01', '2015-01-01' , 1);
  
  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextval, 'Snaky' , 'Cobra', 'M',
  '2003-10-01', null , 3); /*to_date('2003/10/01', 'yyyy/mm/dd') in Oracle*/
  
  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextval, 'Opera' , 'lion', 'F',  
  '2008-11-11', null , 1);
  
  
  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextvAL, 'Donald' , 'turtle', 'M', 
  '2010-01-01', '2010-01-01', 3);