	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'MAMMALS');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'BIRDS');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'REPTILES');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'ADMINISTRATION');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'SECURITY');
	INSERT INTO DIVISIONS (id, NAME) VALUES (SEQ_DIVISONS.NEXTVAL, 'CLEANING');

  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Ala' , 'Abranowska' , 'f', null, 'Mammals', 1);
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Beata', 'Brunowska', 
  'F', null, 'Birds', 2); 
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Cezary', 'Cejrowski', 'M', null, 'Reptiles', 3);
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Dominik' , 'Dmowski',  'M', null, null, 4);
  
  INSERT INTO STAFF (id, NAME, SURNAME, GENDER, SUPERVISOR_ID, SPECIALIZATION, DIVISION_ID) VALUES 
  (SEQ_STAFF.nextval, 'Ewa', 'Edek',  'F', null, null, 4);

  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextval, 'Bruno' , 'lion', 'M',
  '2003-01-01', '2005-01-01' , 1);
  
  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextval, 'Eleonora' , 'Cobra', 'M',
  '2003-10-01', null , 3); /*to_date('2003/10/01', 'yyyy/mm/dd') in Oracle*/
  
  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextval, 'Amelia' , 'lion', 'F',  
  '2008-11-11', null , 1);
  
  
  INSERT INTO ANIMALS (ID, NAME, SPIECES, GENDER, BIRTH_DATE,
  ARRIVAL_DATE, RESPONSIBLE_PERSON_ID) VALUES
  (SEQ_ANIMALS.nextvAL, 'Dominik' , 'turtle', 'M', 
  '2010-01-01', '2010-01-01', 3);