drop table if exists ANIMALS;
drop table if exists STAFF;
drop table if exists DIVISIONS;

DROP SEQUENCE IF EXISTS SEQ_STAFF;
DROP SEQUENCE IF EXISTS SEQ_DIVISONS;
DROP SEQUENCE IF EXISTS SEQ_ANIMALS;

CREATE TABLE IF NOT EXISTS DIVISIONS(
ID INTEGER PRIMARY KEY,
uuid UUID DEFAULT random_uuid(),
NAME VARCHAR(64));

CREATE TABLE IF NOT EXISTS STAFF
(
ID INTEGER PRIMARY KEY,
uuid UUID DEFAULT random_uuid(),
NAME VARCHAR(64) NOT NULL,
SURNAME VARCHAR(64) NOT NULL,
GENDER CHAR (1),
SUPERVISOR_ID INTEGER,
SPECIALIZATION VARCHAR(64),
DIVISION_ID INTEGER,
FOREIGN KEY (SUPERVISOR_ID)
      REFERENCES STAFF (ID) ,
FOREIGN KEY (DIVISION_ID)
      REFERENCES DIVISIONS (ID)    
 );

CREATE TABLE IF NOT EXISTS ANIMALS
(
ID INTEGER PRIMARY KEY,
uuid UUID DEFAULT random_uuid(),
NAME VARCHAR(64),
SPIECES VARCHAR(64),
GENDER CHAR (1) NOT NULL,
BIRTH_DATE DATE,
ARRIVAL_DATE DATE,
RESPONSIBLE_PERSON_ID INTEGER,
FOREIGN KEY (RESPONSIBLE_PERSON_ID)
      REFERENCES STAFF (ID) 
);

CREATE SEQUENCE IF NOT EXISTS SEQ_STAFF
  INCREMENT BY 1 
  START WITH 1;
  
CREATE SEQUENCE IF NOT EXISTS SEQ_DIVISONS
  INCREMENT BY 1 
  START WITH 1;

CREATE SEQUENCE IF NOT EXISTS SEQ_ANIMALS
  INCREMENT BY 1 
  START WITH 1;