CREATE TABLE ANIMALS(
ID number PRIMARY KEY,
NAME VARCHAR2(64 BYTE),
SPIECES Varchar(64 BYTE),
GENDER CHAR (1 BYTE) NOT NULL,
BIRTH_DATE DATE,
ARRIVAL_DATE DATE,
RESPONSIBLE_PERSON_ID NUMBER);

CREATE TABLE STAFF(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(64 BYTE) NOT NULL,
SURNAME VARCHAR2(64 BYTE) NOT NULL,
GENDER CHAR (1 BYTE),
SUPERVISOR_ID NUMBER,
SPECIALIZATION VARCHAR2(64 BYTE),
DIVISION_ID NUMBER);

CREATE TABLE DIVISIONS(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(64 BYTE));

CREATE SEQUENCE IF NOT EXISTS SEQ_STAFF
  INCREMENT BY 1 
  START WITH 1;
  
CREATE SEQUENCE IF NOT EXISTS SEQ_DIVISONS
  INCREMENT BY 1 
  START WITH 1;

CREATE SEQUENCE IF NOT EXISTS SEQ_ANIMALS
  INCREMENT BY 1 
  START WITH 1;